package DAL;
// Generated 19-jan-2015 21:20:20 by Hibernate Tools 4.3.1



/**
 * Druiftbl generated by hbm2java
 */
public class Druiftbl  implements java.io.Serializable {


     private Integer id;
     private String naam;

    public Druiftbl() {
    }

    public Druiftbl(String naam) {
       this.naam = naam;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }




}


