package DAL;
// Generated 19-jan-2015 21:20:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Fototbl generated by hbm2java
 */
public class Fototbl  implements java.io.Serializable {


     private Integer id;
     private String naam;
     private String filenaam;
     private Set wijnhuistbls = new HashSet(0);
     private Set wijntbls = new HashSet(0);

    public Fototbl() {
    }

	
    public Fototbl(String naam, String filenaam) {
        this.naam = naam;
        this.filenaam = filenaam;
    }
    public Fototbl(String naam, String filenaam, Set wijnhuistbls, Set wijntbls) {
       this.naam = naam;
       this.filenaam = filenaam;
       this.wijnhuistbls = wijnhuistbls;
       this.wijntbls = wijntbls;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public String getFilenaam() {
        return this.filenaam;
    }
    
    public void setFilenaam(String filenaam) {
        this.filenaam = filenaam;
    }
    public Set getWijnhuistbls() {
        return this.wijnhuistbls;
    }
    
    public void setWijnhuistbls(Set wijnhuistbls) {
        this.wijnhuistbls = wijnhuistbls;
    }
    public Set getWijntbls() {
        return this.wijntbls;
    }
    
    public void setWijntbls(Set wijntbls) {
        this.wijntbls = wijntbls;
    }




}


