package DAL;
// Generated 19-jan-2015 21:20:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Wijntypetbl generated by hbm2java
 */
public class Wijntypetbl  implements java.io.Serializable {


     private Integer id;
     private String naam;
     private Set wijntbls = new HashSet(0);

    public Wijntypetbl() {
    }

	
    public Wijntypetbl(String naam) {
        this.naam = naam;
    }
    public Wijntypetbl(String naam, Set wijntbls) {
       this.naam = naam;
       this.wijntbls = wijntbls;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public Set getWijntbls() {
        return this.wijntbls;
    }
    
    public void setWijntbls(Set wijntbls) {
        this.wijntbls = wijntbls;
    }

    @Override
    public String toString() {
        return "Wijntypetbl{" + "wijntbls=" + wijntbls + '}';
    }




}


