package DAL;
// Generated 19-jan-2015 21:20:20 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.math.RoundingMode;

/**
 * Wijntbl generated by hbm2java
 */
public class Wijntbl implements java.io.Serializable {

    private Integer id;
    private Fototbl fototbl;
    private Wijnhuistbl wijnhuistbl;
    private Wijntypetbl wijntypetbl;
    private String naam;
    private String platter;
    private int jaar;
    private BigDecimal prijsKarton;
    private byte aantalKarton;
    private BigDecimal prijs;
    private BigDecimal volume;
    private String omschrijving;
    private byte flags;

    public Wijntbl() {
    }

    public Wijntbl(Fototbl fototbl, Wijnhuistbl wijnhuistbl, Wijntypetbl wijntypetbl, String naam, String platter, int jaar, BigDecimal prijsKarton, byte aantalKarton, BigDecimal prijs, BigDecimal volume, String omschrijving, byte flags) {
        this.fototbl = fototbl;
        this.wijnhuistbl = wijnhuistbl;
        this.wijntypetbl = wijntypetbl;
        this.naam = naam;
        this.platter = platter;
        this.jaar = jaar;
        this.prijsKarton = prijsKarton;
        this.aantalKarton = aantalKarton;
        this.prijs = prijs;
        this.volume = volume;
        this.omschrijving = omschrijving;
        this.flags = flags;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Fototbl getFototbl() {
        return this.fototbl;
    }

    public void setFototbl(Fototbl fototbl) {
        this.fototbl = fototbl;
    }

    public Wijnhuistbl getWijnhuistbl() {
        return this.wijnhuistbl;
    }

    public void setWijnhuistbl(Wijnhuistbl wijnhuistbl) {
        this.wijnhuistbl = wijnhuistbl;
    }

    public Wijntypetbl getWijntypetbl() {
        return this.wijntypetbl;
    }

    public void setWijntypetbl(Wijntypetbl wijntypetbl) {
        this.wijntypetbl = wijntypetbl;
    }

    public String getNaam() {
        return this.naam;
    }

    public void setNaam(String naam) {
        this.naam = naam;
    }

    public String getPlatter() {
        return this.platter;
    }

    public void setPlatter(String platter) {
        this.platter = platter;
    }

    public int getJaar() {
        return this.jaar;
    }

    public void setJaar(int jaar) {
        this.jaar = jaar;
    }

    public BigDecimal getPrijsKarton() {
        return this.prijsKarton;
    }

    public void setPrijsKarton(BigDecimal prijsKarton) {
        this.prijsKarton = prijsKarton;
    }

    public byte getAantalKarton() {
        return this.aantalKarton;
    }

    public void setAantalKarton(byte aantalKarton) {
        this.aantalKarton = aantalKarton;
    }

    public BigDecimal getPrijs() {
        BigDecimal d = this.prijs.divide(prijs, 10, RoundingMode.CEILING);
        return this.prijs.divide(prijs, 10, RoundingMode.CEILING);
//        return this.prijs;
    }

    public String getPrijsString() {
        BigDecimal p = this.prijs;
        BigDecimal tien = new BigDecimal("10");
        p = p.divide(tien, 2, RoundingMode.CEILING);
        return p + " €";
    }

    public void setPrijs(BigDecimal prijs) {
        this.prijs = prijs;
    }

    public BigDecimal getVolume() {
        return this.volume;
    }

    public void setVolume(BigDecimal volume) {
        this.volume = volume;
    }

    public String getOmschrijving() {
        return this.omschrijving;
    }

    public void setOmschrijving(String omschrijving) {
        this.omschrijving = omschrijving;
    }

    public byte getFlags() {
        return this.flags;
    }

    public void setFlags(byte flags) {
        this.flags = flags;
    }

}
