package DAL;
// Generated 19-jan-2015 21:20:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Wijnhuistbl generated by hbm2java
 */
public class Wijnhuistbl  implements java.io.Serializable {


     private Integer id;
     private Fototbl fototbl;
     private String naam;
     private String omschrijving;
     private String streek;
     private String eigenaar;
     private String link;
     private Set wijntbls = new HashSet(0);

    public Wijnhuistbl() {
    }

	
    public Wijnhuistbl(Fototbl fototbl, String naam, String omschrijving, String streek, String eigenaar, String link) {
        this.fototbl = fototbl;
        this.naam = naam;
        this.omschrijving = omschrijving;
        this.streek = streek;
        this.eigenaar = eigenaar;
        this.link = link;
    }
    public Wijnhuistbl(Fototbl fototbl, String naam, String omschrijving, String streek, String eigenaar, String link, Set wijntbls) {
       this.fototbl = fototbl;
       this.naam = naam;
       this.omschrijving = omschrijving;
       this.streek = streek;
       this.eigenaar = eigenaar;
       this.link = link;
       this.wijntbls = wijntbls;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Fototbl getFototbl() {
        return this.fototbl;
    }
    
    public void setFototbl(Fototbl fototbl) {
        this.fototbl = fototbl;
    }
    public String getNaam() {
        return this.naam;
    }
    
    public void setNaam(String naam) {
        this.naam = naam;
    }
    public String getOmschrijving() {
        return this.omschrijving;
    }
    
    public void setOmschrijving(String omschrijving) {
        this.omschrijving = omschrijving;
    }
    public String getStreek() {
        return this.streek;
    }
    
    public void setStreek(String streek) {
        this.streek = streek;
    }
    public String getEigenaar() {
        return this.eigenaar;
    }
    
    public void setEigenaar(String eigenaar) {
        this.eigenaar = eigenaar;
    }
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }
    public Set getWijntbls() {
        return this.wijntbls;
    }
    
    public void setWijntbls(Set wijntbls) {
        this.wijntbls = wijntbls;
    }




}


